config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'likes/destroy'

  # when we receive a get request with the '/' url we invoke the index application
  # # within the home controller
  # get '/' => "home#index", as: :home # home_path
  #   # controller#action

  root 'home#index'

  get '/contact' => "home#contact" #Rails auto-generates a URL helper called contact_path
                                  # and contact_url

  post '/contact_submit' => 'home#contact_submit'


  get '/contact_submit' => 'home#contact_submit'

  resources :questions, shallow: :true do
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy, :update]
    # when we define a route within the block for 'resources' we make the route
    # asscociated with the questions controller. We have different options we
    # can use with these routes:
    # on: :collection => this makes the route not include an :id or :question_id
    # in it. This is very similar to the 'index' action url
    # this is equivalent to:
    # get '/questions/search' => 'questions#search', as: :search_questions
    get :search, on: :collection
    # on: :member => this makes the route include an ':id' this is usually
    # useful for routes on actions that are related to a given recoredd
    # this is somewhat similar to the 'edit' action
    # get '/questions/:id/flag' => 'questions#flag' as: :flag_question
    get :flag, on: :member


    # if you don't include any option (neither collection nor member) then
    # you're defining a nested resource, which means it will include
    # ':question_id' in the URL
    # would be POST '/questions/:question_id/approve' => 'questions#approve',
    # as: :question_approve
    post :approve


    # nesting the answers resources within the questions resources block
    # will make it so that every 'answers' route is prefixed with :
    # '/questions/:question_id'. We will need the 'question_id' to create
    # or answer associated with a question so we will stick with this way of
    # defining the routes. The route helpers will also have 'question_' prefix
    resources :answers, only: [:create, :destroy]
  end

    resources :users, only: [:new, :create]

    resources :sessions, only: [:new, :create, :destroy] do
      delete :destroy, on: :collection
    end



  # get '/questions/new' => 'questions#new', as: :new_question
  #
  # post '/questions' => 'questions#create', as: :questions
  #
  # get '/questions/:id' => 'questions#show', as: :question
  #
  # # the url helpers (when we set it using 'as') is only concerned about the URL
  # # and not the VERB. So even if we have two routes with the same url and
  # # different verbs, the url helper should be the same
  #
  # get '/questions' => 'questions#index'
  #
  # get '/questions/:id/edit' => 'questions#edit', as: :edit_question
  #
  # patch '/questions/:id' => 'questions#update'
  #
  # delete '/questions/:id' => 'questions#destroy'

end

app/models/question.rb
class Question < ApplicationRecord

  # this sets up the one to many association from the question model. You
  # always provide plural form of the model, in this case answers
  # this will give us handy methods to easily work with the association
  # You must provide a 'dependent' option to your 'has_many'
  has_many :answers, lambda { order(created_at: :DESC) }, dependent: :destroy
  # has_many :answers, dependent: :nullify -- updates question_id's to 'NULL'
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  belongs_to :user

  validates :title, presence: true, uniqueness: {case_sensitive: false,
                                                 message: 'must be unique'}

  # with scope we validate that the combination of two fields is unique. In the
  # example below, we're validating that the combination of title/body is unique
  # -only invalid if a question and title aren't unique
  validates :body, length: {minimum: 5, message: 'title must have more letters'},
                   uniqueness: {scope: :title}

  validates :view_count, numericality: { greater_than_or_equal_to: 0 }

  # can create custom validations
  validate :no_monkey

  after_initialize :set_defaults
  before_validation :titleize_title

  # scope :recent_ten, lambda {limit(10).order(created_at: :desc)}

  def self.recent_ten
    limit(10).order(created_at: :desc)
  end

  def user_full_name
    if user
      user.full_name
    else
      'Anonymous'
    end
  end

  def like_for(user)
    likes.find_by(user: user)
  end

  def vote_value
    votes.up.count - votes.down.count
  end


  private

  def no_monkey
    if title && title.include?('monkey')
      errors.add(:title, 'No fucking monkeys')
    end
  end

  def set_defaults
    self.view_count ||= 0
  end

  def titleize_title
    self.title = title.titleize
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # this action is to show the form for creating a new questions
  # URL: /questions/new
  # path helper is: new_question_path
  # before_action method here registers a method (usually private) to
  # be executed just before controller actions. This happens within the
  # same request/response cycle which means if you define an instance
  # variable it will be available within action
  # you can optionally give options: 'only' or 'except' to restrict the actions
  # that this 'before_action' method applies to
  before_action :authenticate_user, except: [:index, :show]
  before_action :find_question, only: [:edit, :update, :destroy, :show]
  before_action :authorize_access, only: [:edit, :update, :destroy]
  # better to use only because you are more explicit, if you add methods later
  # they will be included in the before_action

  #before_action's will be called in the order in which they are defined

  def new
    @question = Question.new
  end


  # this action is to handle creating a new question after submitting the form
  # that was shown in the new action
  def create
    # Question.create question_params

    # checks if question passes validations or not:
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
    # render --- basically just print or doc.write
      # redirect_to question_path({id: @question.id}) OR
      flash[:notice] = "Question created!"
      redirect_to question_path(@question)
    else
      #re-renders the new question page
      flash.now[:alert] = 'Please see errors below:'
      render :new
    end
  end

  # this action shows info about specific question
  # URL: /questions/:id
  # method: GET
  def show
    # find_question
    # render plain: "In show action"
    @answer = Answer.new
    @like = @question.like_for(current_user)
  end

  # this action shows a listing of all the questions
  # URL: /questions
  # method: GET
  def index
    @questions = Question.order(created_at: :desc)
  end

  # this action is to show a form pre-populated with the question's data
  # URL /questions/:id/edit
  # method: GET
  def edit
    # find_question
  end

  # this action is to capture the params from the form submission from the
  # edit action in order to update a question
  # URL: /questions/:id
  # method: PATCH
  def update
    # find_question
    # question_params = params.require(:question).permit([:title, :body])
    if  @question.update question_params
    flash[:notice] = "Question updated!"
    # also can add 'notice: 'Question updated' to redirect line- same thing
    # only works for redirect though, not render
    redirect_to question_path(@question)
    else
      flash.now[:alert] = 'Please see errors below:'
      render :edit
    end

    # render plain: 'in update action'
  end

  # this action handles deleting a question
  # URL: /questions/:id
  # method: DELETE
  def destroy
    # find_question
    @question.destroy
    flash[:notice] = "Question deleted!"
    redirect_to questions_path
    # render plain: 'hey'
  end

  private #because it's not an action

  def authorize_access
    unless can? :manage, @question
      # head :unauthorized -- this will send an empty HTTP response with 401 code
      redirect_to root_path, notice: "Access denied"
    end
  end

  def question_params
    question_params = params.require(:question).permit([:title, :body])
  end

  def find_question
    @question = Question.find params[:id]
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= @question.errors.full_messages.join", " %>
<%= form_for @question do |f| %>
  <div>

    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit btn_label%>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>
<%# if the object you pass to the form_for is persisted (has an id in the DB)
then Rails will automatically make the form submit a PATCH request with URL
in this case question_path(@question) (same as show link with PATCH
request).
@question variable is persisted in this case so it will have a title and a body
so those will be prepopulated in their respective fields%>
<!-- <%## form_for @question do |f| %>
  <div>

    <%# f.label :title %>
    <%# f.text_field :title %>
  </div>
  <div>
    <%# f.label :body %>
    <%# f.text_area :body %>
  </div> -->

  <%# f.submit %>
<%= render 'form', {btn_label: 'Update'}%>

app/views/questions/index.html.erb
<h1>All questions</h1>

<% @questions.each do |q| %>
  <%= link_to q.title, question_path(q) %>
  <hr>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%# @question.errors.full_messages.join", " %>

<%# We use form_for when we're creating a form related to a Rails model,
first argument will be activerecord object. If first argument is a new instance of
the ActiveRecord class, for example, Question.new, then the form will automatically
send a POST request to the standard create action url which is in this case:
questions_path %>
<%# form_for @question do |f| %>
  <!-- <div> -->
    <%# we can use f.label and f.text_field to generate a label/text input group
    in this case, 'title' must be an attribute for the variable you pass to
    form_for which is @question in this case
    The label will have a 'for' attribute that matches the ID of the generated
    input field for the title
    The title input field will have a name attribute that is model_type[field]
    In the example below, the 'name' attribue for the input field will be:
    question[title] %>
    <%# f.label :title %>
    <%# f.text_field :title %>
  <!-- </div>
  <div> -->
    <%# f.label :body %>
    <!-- <%# f.text_area :body %>
  </div> -->
<%# this will automatically generate a submit button. The label for the button
will depend on the @question variable. If @question is a new instance, then the
label of the button will be 'Create #{model name capitalized}'.
If you're not happy with label, pass the label as a first argument--
f.submit 'Create' %>
  <%# f.submit %>
<%#end %>

<%= render 'form', { btn_label: 'Submit' } %>
<!-- This line will look for partial named conventionally '_form.html.erb'
     within the same folder as this file which is: /app/views/questions/.
     Partials will have access to the same instance variable as the template
     they are rendered within. In this case the '_form' partial will have access
     to @question variable.
     If you want to pass a local variable, then you will have to have to do
     that explicitly
     In this case there will be a local variable called 'btn_label' withing
     the '_form' partial and it will have the value of 'Submit' -->

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>
<h3>Created by <%= @question.user_full_name %></h3>
<br>
<h3><%= @question.body %></h3>
<% if can? :manage, @question %>
<%= link_to 'edit', edit_question_path(@question) %>
<%= link_to 'delete', question_path(@question),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
<% else %>
<% end %>
<% if user_signed_in? && can?(:like, @question) %>
<% like = @question.like_for(current_user) %>
  <% if like.present? %>
  <%= link_to '🚽 Un-like', like_path(like), method: :delete %>
  <% else %>
  <%= link_to 'Like 🍑', question_likes_path(@question), method: :post %>
  <% end %>
<% end %>
(<%= pluralize @question.likes.count, "like" %>)
<%# form_for @answer, url: question_answers_path(@question) do |f| %>

<section class="vote-widget">
  <%= upvote_link @question %>
  <%= downvote_link @question %>
  <%= @question.vote_value %>
</section>

<h2>All answers</h2>
<%= @answer.errors.full_messages.join(', ') %>
<%= form_for [@question, @answer] do |f| %>
<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %>
<% @question.answers.each do |ans| %>
  <%= ans.body %> | <%= ans.user_full_name %>
  <% if can? :delete, ans %>
  <%= link_to 'delete', answer_path(ans),
                        method: :delete,
                        data: { confirm: 'are you sure?'} %>
  <% end %>
  <hr>

<% end %>